### ISSUE TITLE
Generating .dat file - backend url

### ISSUE THREAD

**Issue by ccamacho89** [WEHI-labatlab/HE_GUI#14]
The backend url for the mibitracker is not something I am familiar with. Would it be possible to provide a bit more detail on where users may be able to find or obtain this url? Thanks.

**Comment by christianrickert** [comment]
You'll find the URL in your MIBItracker "About" section.
> https://YOURDOMAIN.ionpath.com/tracker/about

The MIBItracker API URL would then be something like:

> Backend URL (For API usage and MIBI/O integration): https://backend-dot-mibitracker-YOURDOMAIN.appspot.com

It's a bit hidden, agreed.

**Comment by yokotenka** [comment]
Hi @ccamacho89 thanks for raising this. Just to add to @christianrickert , you can find the backend url on MIBI-tracker. Once you login, you need to press your profile on the top right, then press "About"
![Screen Shot 2022-11-04 at 10 49 53 am](https://user-images.githubusercontent.com/70961284/199856170-240811f4-25bc-45aa-9bcb-0c784221f893.png)

You should be able to find it under the "MIBItracker API".

![Screen Shot 2022-11-04 at 10 51 23 am](https://user-images.githubusercontent.com/70961284/199856355-9197c09c-5793-407a-b35e-5ef4b971365d.png)

I will include this in the wiki

**Comment by ccamacho89** [comment]
This solved my problem. Thank you so much for your help.
