### ISSUE TITLE
Supported operating system

### ISSUE THREAD

**Issue by christianrickert** [WEHI-labatlab/HE_GUI#7]
Do you want to support multiple operating systems or is the main target platform Windows?
All MIBI operator stations (CAC) are Windows 10, so it would make sense to limit the OS support.
However, it might also be useful to keep access open for MacOS or Linux.

Are there any dependencies that require Windows?

**Comment by yokotenka** [comment]
There aren't any Windows specific dependencies. Most my colleagues operate on a MacOS (include myself) so I think it will be most convenient for me to have Mac support.

**Comment by christianrickert** [comment]
I'm switching between OS, depending on requirements:

![image](https://user-images.githubusercontent.com/19319377/172416376-0ab3cb17-ab94-4ef2-ad15-f7fe5005a75b.png)

There's definitely an advantage in being able to prepare FoVs ahead of time
on a different system than Windows.

P.S.: I'll update the readme to not force a specific file path style (separator).

**Comment by yokotenka** [comment]
> There's definitely an advantage in being able to prepare FoVs ahead of time
on a different system than Windows.

Yes, I totally agree

> P.S.: I'll update the readme to not force a specific file path style (separator).

Awesome thanks! I will close this issue
